name: Publish dotsef-hosts

on:
  push:
    branches:
    - main

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
 
permissions:
  packages: write
  contents: write

jobs:
  dotsef-hosts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
      - run: dotnet pack -c Release
      - run: dotnet nuget push Hosts.Cli/bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
      - run: nbgv tag
      - run: git push origin v$(nbgv get-version -v NugetPackageVersion)
        shell: bash
